# Default values for prometheus-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: minio-job-cluster
          metrics_path: /minio/v2/metrics/cluster
          scheme: http
          static_configs:
          - targets: [minio-service.default.svc.cluster.local]
        - job_name: minio-job-bucket
          metrics_path: /minio/v2/metrics/bucket
          scheme: http
          static_configs:
          - targets: [minio-service.default.svc.cluster.local]
        - job_name: minio-job-resource
          metrics_path: /minio/v2/metrics/resource
          scheme: http
          static_configs:
          - targets: [minio-service.default.svc.cluster.local]