# Default values for prometheus-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus-adapter:
  prometheus:
    # Value is templated
    url: http://prometheus-operated.monitoring.svc.cluster.local
    port: 9090
    path: ""
  rules:
    custom:
    - seriesQuery: 'minio_s3_requests_total{api="getobject"}'
      resources:
        overrides:
          namespace: 
            resource: "namespace"
          pod_name: 
            resource: "pod"
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'minio-job-resource'
          metrics_path: /minio/v2/metrics/resource
          scheme: http
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              target_label: namespace
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              action: keep
            - source_labels: [__meta_kubernetes_pod_name]
              regex: (minio-server-.*)
              target_label: pod_name
            - source_labels: [__meta_kubernetes_pod_name]
              regex: minio-server-.*
              action: keep
        - job_name: 'minio-job-bucket'
          metrics_path: /minio/v2/metrics/bucket
          scheme: http
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              target_label: namespace
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              action: keep
            - source_labels: [__meta_kubernetes_pod_name]
              regex: (minio-server-.*)
              target_label: pod_name
            - source_labels: [__meta_kubernetes_pod_name]
              regex: minio-server-.*
              action: keep
        - job_name: 'minio-job-cluster'
          metrics_path: /minio/v2/metrics/cluster
          scheme: http
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              target_label: namespace
            - source_labels: [__meta_kubernetes_namespace]
              regex: (.*)
              action: keep
            - source_labels: [__meta_kubernetes_pod_name]
              regex: (minio-server-.*)
              target_label: pod_name
            - source_labels: [__meta_kubernetes_pod_name]
              regex: minio-server-.*
              action: keep