# Default values for s3www.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod
replicas: 2

image:
  repository: maymeow/s3www
  tag: latest

resources:
  limits:
    cpu: 20m
    memory: 20Mi
  requests:
    cpu: 5m
    memory: 5Mi

hpa:
  minReplicas: 2
  maxReplicas: 3
  metricName: container_memory_usage
  metricThreshold: 15m
