---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script-config
data:
  minio-script.sh: |
    #!/bin/sh
    cd /

    echo "Executing sidecar script..."
    apk add curl
    FLAG=0

    #   Downloading Minio Client
    ARCHITECTURE=$(arch)
    if [ "$ARCHITECTURE" == "x86_64" ]; then
        wget -O mc https://dl.min.io/client/mc/release/linux-amd64/mc
    else
        wget -O mc https://dl.min.io/client/mc/release/linux-arm64/mc
    fi
    chmod +x mc

    #   Downloading gif
    wget -O giphy.gif https://media.giphy.com/media/VdiQKDAguhDSi37gn1/giphy.gif

    while [ $FLAG == 0 ]
    do
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $MINIO_ENDPOINT/minio/health/live)
        echo $STATUS_CODE
        if [ "$STATUS_CODE" == "200" ]; then
            echo "Minio service is active" 
            ./mc alias set minioclient $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
            ./mc mb minioclient/static-website-bucket
            ./mc anonymous set download minioclient/static-website-bucket
            ./mc cp giphy.gif minioclient/static-website-bucket

            FLAG=1
        else
            echo "Waiting for minio service to become active"
            sleep 5
        fi
    done