---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-server
          image: {{ .Values.minioServer.image.repository }}:{{ .Values.minioServer.image.tag }}
          resources:
            {{- toYaml .Values.minioServer.resources | nindent 12 }}
          command:
          - /bin/bash
          - -c
          args:
          - minio server /data --console-address :9001
          env:
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    name: {{ .Chart.Name }}-secret
                    key: ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                    name: {{ .Chart.Name }}-secret
                    key: SECRET_KEY
          ports:
          - containerPort: {{ .Values.minioServer.containerPort }}
            hostPort: {{ .Values.minioServer.containerPort }}
