---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Chart.Name }}-server
  minReplicas: {{ .Values.minioServer.hpa.minReplicas }}
  maxReplicas: {{ .Values.minioServer.hpa.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: {{ .Values.minioServer.hpa.metricName }}
      target: 
        type: Utilization
        averageValue: {{ .Values.minioServer.hpa.metricThreshold }}
