---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
type: Opaque
data:
  ACCESS_KEY: {{ .Values.access_key }}
  SECRET_KEY: {{ .Values.secret_key }}