---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  ACCESS_KEY: {{ .Values.access_key | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret_key | b64enc | quote }}