---
kind: Service 
apiVersion: v1 
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.minioServer.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.minioServer.service.targetPortApi }}
  - name: cluster
    port: 9000
    targetPort: {{ .Values.minioServer.service.targetPortApi }}
  - name: console
    port: 9001
    targetPort: {{ .Values.minioServer.service.targetPortConsole }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.minioServer.service.targetPortApi }}
  selector:
    app: {{ .Chart.Name }}