---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-server
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-server
        image: {{ .Values.minioServer.image.repository }}:{{ .Values.minioServer.image.tag }}
        resources:
        {{- toYaml .Values.minioServer.resources | nindent 8 }}
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: {{ .Values.minioServer.prometheus.authType }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: SECRET_KEY
        args:
        - server
        - http://minio-server-{0...1}.minio.default.svc.cluster.local/data
        - --console-address
        - :9001
        ports:
        - containerPort: {{ .Values.minioServer.containerPort }}
          hostPort: {{ .Values.minioServer.containerPort }}
        # These volume mounts are persistent. Each pod in the Statefulset
        # gets a volume mounted based on this field.
        volumeMounts:
        {{- toYaml .Values.minioServer.volumeMounts | nindent 8 }}
      volumes:
      {{- toYaml .Values.minioServer.volume | nindent 6 }}
