# Default values for minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

access_key: bWluaW8=
secret_key: bWluaW8xMjM=

minioJob:
  minioEndpoint: http://minio-service:80
  gifEndpoint: https://media.giphy.com/media/VdiQKDAguhDSi37gn1/giphy.gif

minioServer:
  prometheus:
    authType: public
  containerPort: 9000
  service:
    type: ClusterIP
    targetPortApi: 9000
    targetPortConsole: 9001