# Default values for minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

access_key: minio
secret_key: minio123

minioJob:
  image: 
    repository: alpine
    tag: 3.19.1
  minioEndpoint: http://minio-service:80
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  volumeMounts:
    - name: script-volume
      mountPath: /script
  volume:
    - name: script-volume
      configMap:
        name: minio-script-config
        defaultMode: 0755

minioServer:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2023-10-24T04-42-36Z
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"
  containerPort: 9000
  service:
    type: ClusterIP
    port: 80
    targetPort: 9000
